title: Olga Pombo
description: Personal Webpage
baseurl: ""
url: "https://olgapombo.github.io"

# Build settings
markdown: kramdown
permalink: /:basename.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
    
